"""Added User model

Revision ID: 81a706c8c092
Revises: 0584f8e3ce7d
Create Date: 2020-02-28 14:55:23.328764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a706c8c092'
down_revision = '0584f8e3ce7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=25), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_cookies_cookie_name'), 'cookies', ['cookie_name'], unique=False)
    op.drop_index('ix_new_cookies_cookie_name', table_name='cookies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_new_cookies_cookie_name', 'cookies', ['cookie_name'], unique=False)
    op.drop_index(op.f('ix_cookies_cookie_name'), table_name='cookies')
    op.drop_table('users')
    # ### end Alembic commands ###
